### ISSUE TITLE
Log directory not created automatically

### ISSUE THREAD

**Issue by RaoulHeese** [gan-police/frequency-forensics#16]
When training models, the resulting model file is stored in `./log/,` which may not exist:
https://github.com/gan-police/frequency-forensics/blob/dad3cc17d824537788fdf68cb517bed3d7f2ae6a/src/freqdect/train_classifier.py#L264-L272
Folder should be created on demand, if not existent.

**Comment by v0lta** [comment]
https://github.com/gan-police/frequency-forensics/blob/11eec799e68e3fd96a2d5fec603e0ff73b6a3948/src/freqdect/train_classifier.py#L382 takes care of this issue.
