### ISSUE TITLE
Could you share the pretrained classiffer please?

### ISSUE THREAD

**Issue by lcd21** [gan-police/frequency-forensics#22]
Your work is enlightening. Could you share the pre-trained model of the classifier, please? Thank you.

**Comment by v0lta** [comment]
I have uploaded a regression model as defined in [model.py](https://github.com/gan-police/frequency-forensics/blob/74f3c1da3528edc3d7eaf9533e266eba8910215c/src/freqdect/models.py#L151) into [google-drive](https://drive.google.com/file/d/1FtT_aRNBhw0_qPhAhKJSWLTSs2-FIZ2t/view?usp=sharing) .
